### ISSUE TITLE
Random plugin issue when installing a plugin

### ISSUE THREAD

**Issue by JoMas971** [SamVerschueren/gulp-cordova-plugin#18]
Hello,

I have a totally random issue when i'm using this repo. The first time i've launched my task, it's always working, but sometimes, i have an issue telling me that it can't fetch one of my plugins (the plugin change all the time : sometimes it's cordova-plugin-whitelist, sometimes it's org.apache.cordova.inappbrowser... etc). It seems to have an issue with plugman, because when i delete the .plugman folder and re-run my task, it seems to work better... But not all the times : sometime i still get the issue even if i remove the .plugman folder. So that's not a good solution to delete this folder automatically.

There is my issue :

```
[12:57:48] 'cordova:create' errored after 2.08 s
[12:57:48] Error in plugin 'gulp-cordova-plugin'
Message:
    Failed to fetch plugin cordova-plugin-whitelist@1.2.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: ENOENT, open '/Users/ME/PATH/TO/PROJECT/.plugman/cache/cordova-plugin-whitelist/1.2.0/package.tgz'
```

And there is my gulp task :

```
gulp.task('cordova:create', ['cordova:prepare'], function(cb) {
  var create = require('gulp-cordova-create');
  var plugin = require('gulp-cordova-plugin');

    return gulp.src(paths.distDir)
      .pipe(create(options))
      .pipe(plugin({
    "org.apache.cordova.inappbrowser": "latest",
    "org.apache.cordova.device": "latest",
    "cordova-plugin-console": "1.0.2",
    "cordova-plugin-whitelist": "1.2.0",
    "cordova-plugin-statusbar": "2.0.0",
    "cordova-plugin-file": "3.0.0",
    "cordova-plugin-file-opener2": "2.0.2",
    "cordova-custom-config": "1.1.11"
  }));
});
```

I've tested with all the different usages (simple, array, object) and i have the same result... 
Also, i have a good and stable network connection (100Mb) so it can't be a network issue.
The weirdest part, is that i just need to re-run my task again and again until it's works because it will work at some times... But i can't have this sort of unstable install on production...

Maybe i need to change the plugins order or use the fully qualified git URLs ?
Can also be an old version of plugman or cordova-lib (they've released the version 6.0.0)...

I hope you can help because i'm totally lost/block with that issue.

Thank you in advance and thank you for your work.

**Comment by SamVerschueren** [comment]
What's the version of `gulp-cordova-plugin` you are using? Might be related to https://github.com/SamVerschueren/gulp-cordova-plugin/issues/6 and should be fixed in `v1.2.0`. If not, continue reading :).

---

I created `gulp-cordova` because I had issues when adding more plugins over time during development. Suddenly they failed to install and I had to remove the entire gulp project and recreate everything. And that is actually what I do as well with `gulp-cordova`. Every time I build my cordova app, I remove my `dist` directory and start from scratch. But maybe, you do that as well.

When did this issue started? Is this the first time you experience problems with installing plugins? We had a similar problem in the past.

**Comment by JoMas971** [comment]
I'm using the latest version of `gulp-cordova-plugin` (1.4.0).

But, after reading the latest release note from `codova-lib` [repo](https://github.com/apache/cordova-lib/commit/4328a39276a2ded4bcf1dba7c33bfb9d8f35cfd2) it seems that they've fixed a bench of issues.

> CB-9957 removed support for fetching from Cordova Plugins Registry. Only fetch plugins from **npm** now.
> 
> CB-10274 Make www directory the default for plugman

Maybe that will fix this issue definitely. Need to update `codova-lib` to v6.0.0. What do you think ?

Thanks for your fast answer and thank you for your time.

**Comment by SamVerschueren** [comment]
Thanks for linking the doc. Have to experiment if that fixes the issue, not sure though. It works as expected on my machine.

This is what you can do to test it.
1. Clone this repository on your machine
2. Bump the `cordova-lib` dependency to `6.0.0`
3. Run `npm install`
4. Run `npm link`

Go to your cordova project where you have the gulpfile
1. Uninstall the plugin `npm uninstall gulp-cordova-plugin --save-dev`
2. Link your local version `npm link gulp-cordova-plugin`
3. Test if the gulp task runs

**Comment by JoMas971** [comment]
I also can do a patch to bump-up the `cordova-lib` dependency to `6.0.0` and test it ^^.

But thank you, i'll keep you informed if that fix my issue.

**Comment by SamVerschueren** [comment]
Yes you can, but not sure if the automated tests will indicate if something is up with the current set up as it just works on my machine :). But if it works, feel free to do a PR to bump the version :).

**Comment by JoMas971** [comment]
Ok thanks.

**Comment by JoMas971** [comment]
Ok it seems that it fix my issue. I've done PR https://github.com/SamVerschueren/gulp-cordova-plugin/pull/19.
