### ISSUE TITLE
Ability to delete plugins aswell.

### ISSUE THREAD

**Issue by cameronbourke** [SamVerschueren/gulp-cordova-plugin#4]
Awesome bunch of plugins @SamVerschueren. Any chance you could include the ability to add _and remove_ Cordova plugins?

It would be a massive help when having to strip out certain plugins before creating a production build.

**Comment by SamVerschueren** [comment]
Hi @cameronbourke, can you give an example of a plugin you would add and then later on remove again? If it would be helpfull I can certainly create a plugin for it.

**Comment by cameronbourke** [comment]
@SamVerschueren  Yeah sure! At the moment whenever I go to create a production ipa, I rip out the console plugin, https://github.com/apache/cordova-plugin-console, and then add it back afterwards. It would be awesome to be able to automate that process with gulp.

I already use your plugin to add the console plugin back, it would just be cool to do the same when deleting it.

**Comment by SamVerschueren** [comment]
@cameronbourke Have a look at [gulp-cordova-plugin-remove](https://github.com/SamVerschueren/gulp-cordova-plugin-remove)

**Comment by cameronbourke** [comment]
@SamVerschueren I had a feeling this would be the case haha! Thanks for the hand.
