### ISSUE TITLE
Somethings seems wrong with the cordova registry

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/gulp-cordova-plugin#6]
See PR https://github.com/SamVerschueren/gulp-cordova-plugin/pull/5 for more information.

**Comment by bennybennet** [comment]
I think the problem ist cordova-lib.

using cordova cli 5.x

```
cordova plugin add cordova-plugin-whitelist
> Fetching plugin "cordova-plugin-whitelist" via npm
> npm http GET https://registry.npmjs.org/cordova-plugin-whitelist
```

using gulp-cordova-plugion

```
gulp cordova:plugins
> npm http GET http://registry.cordova.io/cordova-plugin-whitelist
```

as you are using cordova-lib inside of your gulp task, i think the cordova-lib is not up2date. Since 5.0.0 of cordova npm is used as the new plugin registry.

**Comment by SamVerschueren** [comment]
I can try upgrading the `cordova-lib` to the latest version (5.2.0) to see if this makes a difference.

**Comment by SamVerschueren** [comment]
Hi @bennybennet 

In the latest version (1.2.0), I upgraded the cordova-lib to `5.2.0`. You can try if this issue is fixed.

**Comment by bennybennet** [comment]
works! :+1:

**Comment by SamVerschueren** [comment]
Nice. Thanks for testing!
