### ISSUE TITLE
accept arguments

### ISSUE THREAD

**Issue by bennybennet** [SamVerschueren/gulp-cordova-plugin#7]
There are plugins which needs arguments during installation, like phonegap-google-maps: https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-Mac

The command would be:

```
cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
```

**Comment by SamVerschueren** [comment]
I think you can do it like this

``` javascript
.pipe(plugin('plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"'))
```

**Comment by bennybennet** [comment]
No, that's not working. :(
cordova-lib only accepts pluginname@1.0.0 nothing more.

```
[13:53:35]      add plugin.google.maps --variable API_KEY_FOR_ANDROID="YOUR_ANDROID_API_KEY_IS_HERE" --variable API_KEY_FOR_IOS="YOUR_IOS_API_KEY_IS_HERE"
[13:53:35] Plumber found unhandled error:
 Error in plugin 'gulp-cordova-plugin'
Message:
    Invalid attribute predicate
```

**Comment by SamVerschueren** [comment]
Thanks for reporting, will have a closer look into this.

**Comment by SamVerschueren** [comment]
It seems that it is supported by passing an options object as 3rd parameter and pass a `cli_variables` object with the key as variable name and the value as value.

https://github.com/apache/cordova-lib/blob/master/cordova-lib/src/cordova/plugin.js#L137

**Comment by bennybennet** [comment]
Nice, seems like that could be working.
Will you add it?

**Comment by SamVerschueren** [comment]
Yes. Keep you posted on this.

**Comment by SamVerschueren** [comment]
Implemented in v1.2.0. Have a look at the updated documentation regarding the syntax.

**Comment by bennybennet** [comment]
you're awesome sam, will check it out tomorrow.

Am Montag, 17. August 2015 schrieb Sam Verschueren :

> Implemented in v1.2.0. Have a look at the updated documentation regarding
> the syntax.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SamVerschueren/gulp-cordova-plugin/issues/7#issuecomment-131918701
> .

## 

Sent from Gmail Mobile

**Comment by bennybennet** [comment]
It works!! Thanks again Sam.

I do have a little improvement request:
What do you think about the following structure:
As plugins do have versions, you could use the value (atm always "true") for the key (pluginname) for the versions like so:

```
"cordovaDependencies": {
    "cordova-plugin-statusbar": "latest",
    "cordova-plugin-whitelist": "1.0.0",
    "https://github.com/litehelpers/Cordova-sqlcipher-adapter": "1.2.1",
    "cordova-plugin-crosswalk-webview": "latest",
    "cordova-plugin-geolocation": "latest",
    "cordova-plugin-inappbrowser": "latest",
    "uk.co.whiteoctober.cordova.appversion": "latest",
    "com.ionic.keyboard": "latest",
    "https://github.com/kristianhristov/cordova-cookie-master.git": "latest",
    "plugin.google.maps": {
      "version": "latest",
      "variables": {
        "API_KEY_FOR_ANDROID": "YOUR_ANDROID_API_KEY_IS_HERE",
        "API_KEY_FOR_IOS": "YOUR_IOS_API_KEY_IS_HERE"
      }
    }
  }
```

**Comment by SamVerschueren** [comment]
Good suggestion! Will create a new issue for this.

**Comment by SamVerschueren** [comment]
@bennybennet Added in `1.3.0`. See the docs for the changes.

**Comment by bennybennet** [comment]
@SamVerschueren awesome! thanks, will test later.
